version: "3"

services:
  server:
    build:
      context: server
      dockerfile: docker/Dockerfile
#    ports:
#      - "8000:8000"
    expose:
      - 8000
    volumes:
      - "./server:/code"
    depends_on:
      - db

  client:
    build:
      context: client
      dockerfile: docker/Dockerfile
#    ports:
#      - "8080:8080"
    expose:
      - 8001
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - "./client:/app"
      - "/app/node_modules"


  proxy:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=_
      - NGINX_PORT=80
    depends_on:
      - server
      - client

  db:
    image: postgres
    expose:
      - 5432
    ports:
      - "5433:5432" # for dev only!!!
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - "db_data:/var/lib/postgresql/data"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db_data: {}
