"""metric values

Revision ID: 6b909d55f976
Revises: 8b49fa62a840
Create Date: 2023-07-11 11:10:40.593593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b909d55f976'
down_revision = '8b49fa62a840'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_values',
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('split_id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['metric_id'], ['metric.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['result.id'], ),
    sa.ForeignKeyConstraint(['split_id'], ['split.id'], ),
    sa.PrimaryKeyConstraint('result_id', 'split_id', 'metric_id', 'model_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metric_values')
    # ### end Alembic commands ###
