"""model metric split

Revision ID: 8b49fa62a840
Revises: ea287291bb76
Create Date: 2023-07-11 11:02:07.017213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b49fa62a840'
down_revision = 'ea287291bb76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('split',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strat', sa.Integer(), nullable=True),
    sa.Column('test', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('algorithm_id', sa.Integer(), nullable=True),
    sa.Column('hipers', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['algorithm_id'], ['algorithm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model')
    op.drop_table('split')
    op.drop_table('metric')
    # ### end Alembic commands ###
