"""algs

Revision ID: ccf6b799a4ac
Revises: c9d048838c0e
Create Date: 2023-07-11 00:02:11.656189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccf6b799a4ac'
down_revision = 'c9d048838c0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('algorithm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('requirement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('alg_req',
    sa.Column('pre_id', sa.Integer(), nullable=False),
    sa.Column('alg_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alg_id'], ['algorithm.id'], ),
    sa.ForeignKeyConstraint(['pre_id'], ['requirement.id'], ),
    sa.PrimaryKeyConstraint('pre_id', 'alg_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alg_req')
    op.drop_table('requirement')
    op.drop_table('algorithm')
    # ### end Alembic commands ###
